buff_cookies: session=1-TVxUPeBTRrAFuiPVjl7I62LA0BcSDDSLOGocvEamGMQa2024630127
notification_settings:
  check_frequency_minutes: 30
  email: 238@qq.com
password_hash: a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3
watchlist:
  '16995':
    conditions: []
    game: dota2
    goods_id: '16995'
    item_name: 冥灵 天游守卫长尾
  '768983':
    conditions:
    - condition_type: price_threshold
      operator: '>'
      target_field: sell_min_price
      value: 20.0
    game: dota2
    goods_id: '768983'
    item_name: 冥灵 剑心之遗
