buff_cookies: session=1-gr2f959EPPecvUX-M5bCOOLst1NShg37GHiDK9DSyHdF2019559149
notification_settings:
  check_frequency_minutes: 30
  email: 238@qq.com
password_hash: a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3
watchlist:
  '16995':
    conditions: []
    game: dota2
    goods_id: '16995'
    item_name: 冥灵 天游守卫长尾
